import React, { useState, useMemo } from "react";
import { Search, ChevronDown, HelpCircle, Star, Terminal, Database, Layers, Cpu, ShieldCheck,CheckCircle2 } from "lucide-react";

const FAQ_DATA = [
/* ================= CORE JAVA BASICS (1–10) ================= */
{
id:1,cat:"Basics",q:"What is Java?",
points:[
"High-level programming language.",
"Object-oriented in nature.",
"Platform independent.",
"Follows Write Once Run Anywhere.",
"Automatic memory management.",
"Supports multithreading.",
"Used in enterprise applications."
],
tanglish:"Java oru platform-independent OOP language."
},
{
id:2,cat:"Basics",q:"Features of Java",
points:[
"Simple and readable syntax.",
"Object-oriented approach.",
"Platform independent execution.",
"Secure memory handling.",
"Robust error handling.",
"High performance with JIT.",
"Portable across systems."
],
tanglish:"Java features interview-ku romba important."
},
{
id:3,cat:"Basics",q:"Why Java is platform independent?",
points:[
"Compiled into bytecode.",
"Bytecode is OS independent.",
"Executed by JVM.",
"JVM available for every OS.",
"No recompilation needed.",
"Hardware independent.",
"Improves portability."
],
tanglish:"JVM irundhaala Java portable."
},
{
id:4,cat:"Basics",q:"What is JVM?",
points:[
"Executes Java bytecode.",
"Converts bytecode to machine code.",
"Manages runtime memory.",
"Handles garbage collection.",
"Loads class files.",
"Provides execution environment.",
"Platform dependent."
],
tanglish:"Bytecode run pannradhu JVM."
},
{
id:5,cat:"Basics",q:"What is JRE?",
points:[
"Provides runtime environment.",
"Contains JVM.",
"Includes core libraries.",
"Used to run programs.",
"No compiler included.",
"Needed by end users.",
"Supports execution."
],
tanglish:"Run panna JRE podhum."
},
{
id:6,cat:"Basics",q:"What is JDK?",
points:[
"Used for Java development.",
"Contains JRE.",
"Includes compiler.",
"Provides debugging tools.",
"Required for coding.",
"Used by developers.",
"Complete Java package."
],
tanglish:"Develop panna JDK thevai."
},
{
id:7,cat:"Basics",q:"What is Bytecode?",
points:[
"Intermediate code.",
"Generated by compiler.",
"Stored in .class file.",
"Platform independent.",
"Executed by JVM.",
"Improves security.",
"Improves portability."
],
tanglish:"Compiler create panna middle code."
},
{
id:8,cat:"Basics",q:"Compiler vs Interpreter",
points:[
"Compiler converts full code.",
"Interpreter executes line by line.",
"Java uses both.",
"Compiler creates bytecode.",
"Interpreter executes bytecode.",
"Improves speed.",
"Reduces runtime errors."
],
tanglish:"Java rendu perayum use pannum."
},
{
id:9,cat:"Basics",q:"What is Class?",
points:[
"Blueprint of an object.",
"Logical entity.",
"Defines variables.",
"Defines methods.",
"No memory allocation.",
"Used to create objects.",
"Supports OOP."
],
tanglish:"Blueprint dhaan class."
},
{
id:10,cat:"Basics",q:"What is Object?",
points:[
"Instance of a class.",
"Real-world entity.",
"Has state and behavior.",
"Occupies memory.",
"Created using new.",
"Multiple objects per class.",
"Runtime entity."
],
tanglish:"Real usage dhaan object."
},

/* ================= OOP CONCEPTS (11–30) ================= */
{
id:11,cat:"OOP",q:"What is OOP?",
points:[
"Programming based on objects.",
"Represents real-world entities.",
"Improves reusability.",
"Enhances maintainability.",
"Improves security.",
"Supports scalability.",
"Modular structure."
],
tanglish:"Object base panna programming."
},
{
id:12,cat:"OOP",q:"Encapsulation",
points:[
"Data hiding technique.",
"Binds data and methods.",
"Uses private variables.",
"Accessed via getters/setters.",
"Improves security.",
"Controls access.",
"Reduces coupling."
],
tanglish:"Data hide pannradhu encapsulation."
},
{
id:13,cat:"OOP",q:"Inheritance",
points:[
"Parent-child relationship.",
"Promotes code reuse.",
"Uses extends keyword.",
"Supports overriding.",
"Reduces duplication.",
"Improves maintenance.",
"Single inheritance supported."
],
tanglish:"Parent property child use pannum."
},
{
id:14,cat:"OOP",q:"Polymorphism",
points:[
"Many forms.",
"Same method name.",
"Different implementations.",
"Compile-time polymorphism.",
"Runtime polymorphism.",
"Improves flexibility.",
"Supports dynamic binding."
],
tanglish:"Ore name, different behavior."
},
{
id:15,cat:"OOP",q:"Abstraction",
points:[
"Hides implementation.",
"Shows essential details.",
"Reduces complexity.",
"Improves readability.",
"Uses abstract class.",
"Interface provides full abstraction.",
"Improves design."
],
tanglish:"Thevaiyana detail mattum show."
},
{
id:16,cat:"OOP",q:"Abstract Class",
points:[
"Partial abstraction.",
"Can have methods.",
"Can have variables.",
"Can have constructor.",
"Uses abstract keyword.",
"Supports inheritance.",
"Cannot instantiate."
],
tanglish:"Half abstraction dhaan."
},
{
id:17,cat:"OOP",q:"Interface",
points:[
"Full abstraction.",
"No constructor.",
"Supports multiple inheritance.",
"Methods public by default.",
"Can have default methods.",
"Uses implements keyword.",
"Loose coupling."
],
tanglish:"Full abstraction tool."
},
{
id:18,cat:"OOP",q:"this keyword",
points:[
"Refers current object.",
"Resolves naming conflict.",
"Used in instance methods.",
"Calls constructor.",
"Improves clarity.",
"Avoids ambiguity.",
"Common usage."
],
tanglish:"Current object refer pannum."
},
{
id:19,cat:"OOP",q:"super keyword",
points:[
"Refers parent object.",
"Calls parent constructor.",
"Access parent variables.",
"Used in inheritance.",
"Avoids hiding.",
"Supports overriding.",
"Improves clarity."
],
tanglish:"Parent class access panna super."
},
{
id:20,cat:"OOP",q:"Constructor",
points:[
"Initializes object.",
"Same name as class.",
"No return type.",
"Called automatically.",
"Can be overloaded.",
"Used at object creation.",
"Default or parameterized."
],
tanglish:"Object setup pannradhu."
},

/* ================= STRINGS & ARRAYS (21–30) ================= */
{
id:21,cat:"Strings",q:"String",
points:[
"Immutable object.",
"Stored in string pool.",
"Thread-safe.",
"Memory efficient.",
"Part of java.lang.",
"Commonly used.",
"Cannot be modified."
],
tanglish:"Change panna mudiyatha string."
},
{
id:22,cat:"Strings",q:"String vs StringBuilder",
points:[
"String immutable.",
"StringBuilder mutable.",
"String thread-safe.",
"StringBuilder faster.",
"String stored in pool.",
"StringBuilder not pooled.",
"Performance difference."
],
tanglish:"Speed venumna StringBuilder."
},
{
id:23,cat:"Arrays",q:"Array",
points:[
"Fixed size.",
"Stores same type.",
"Index based.",
"Fast access.",
"Stored in memory.",
"Supports 2D arrays.",
"Size cannot change."
],
tanglish:"Size fix na array."
},
{
id:24,cat:"Arrays",q:"1D vs 2D Array",
points:[
"1D linear structure.",
"2D tabular structure.",
"1D single index.",
"2D row and column.",
"2D nested loops.",
"1D simpler.",
"2D matrices."
],
tanglish:"Table format na 2D."
},
{
id:25,cat:"Arrays",q:"Array vs ArrayList",
points:[
"Array fixed size.",
"ArrayList dynamic.",
"Array stores primitives.",
"ArrayList stores objects.",
"Array faster.",
"ArrayList flexible.",
"Utility methods available."
],
tanglish:"Flexible na ArrayList."
},

/* ================= EXCEPTION HANDLING (31–40) ================= */
{
id:31,cat:"Exception",q:"Exception",
points:[
"Runtime abnormal condition.",
"Disrupts normal flow.",
"Handled using try-catch.",
"Prevents crash.",
"Improves reliability.",
"Recoverable.",
"Part of java.lang."
],
tanglish:"Runtime error dhaan exception."
},
{
id:32,cat:"Exception",q:"Checked Exception",
points:[
"Compile-time checked.",
"Must be handled.",
"Inherits Exception.",
"IOException example.",
"Improves safety.",
"Compiler responsibility.",
"Forced handling."
],
tanglish:"Compile time error."
},
{
id:33,cat:"Exception",q:"Unchecked Exception",
points:[
"Occurs at runtime.",
"Not mandatory to handle.",
"Inherits RuntimeException.",
"NullPointerException example.",
"Programmer mistake.",
"JVM handles.",
"Flexible handling."
],
tanglish:"Runtime-la varradhu."
},
{
id:34,cat:"Exception",q:"try-catch-finally",
points:[
"try risky code.",
"catch handles exception.",
"finally always executes.",
"Used for cleanup.",
"Prevents crash.",
"Multiple catch allowed.",
"Resource management."
],
tanglish:"Error handle panna."
},
{
id:35,cat:"Exception",q:"throw vs throws",
points:[
"throw explicitly throws.",
"throws declares exception.",
"throw inside method.",
"throws in signature.",
"throw one exception.",
"throws multiple allowed.",
"Different purposes."
],
tanglish:"Throw vs responsibility."
},

/* ================= COLLECTIONS (41–60) ================= */
{
id:41,cat:"Collections",q:"Collection Framework",
points:[
"Unified architecture.",
"Stores group of objects.",
"Dynamic size.",
"Reduces coding effort.",
"Provides algorithms.",
"Improves performance.",
"java.util package."
],
tanglish:"Data manage panna framework."
},
{
id:42,cat:"Collections",q:"List Interface",
points:[
"Allows duplicates.",
"Maintains order.",
"Index based.",
"Allows null.",
"Dynamic size.",
"Common implementations.",
"Ordered data."
],
tanglish:"Duplicate allow pannum."
},
{
id:43,cat:"Collections",q:"ArrayList",
points:[
"Dynamic array.",
"Fast access.",
"Allows duplicates.",
"Maintains order.",
"Not synchronized.",
"Allows null.",
"Most used list."
],
tanglish:"Search fast."
},
{
id:44,cat:"Collections",q:"LinkedList",
points:[
"Doubly linked list.",
"Slower access.",
"Faster insertion.",
"More memory.",
"Maintains order.",
"Implements Queue.",
"Flexible."
],
tanglish:"Insert fast."
},
{
id:45,cat:"Collections",q:"Set Interface",
points:[
"No duplicates.",
"No index.",
"Unordered.",
"Fast search.",
"Allows one null.",
"Used for uniqueness.",
"Common implementations."
],
tanglish:"Duplicate avoid panna."
},
{
id:46,cat:"Collections",q:"HashSet",
points:[
"No duplicates.",
"No order.",
"Allows one null.",
"Fast performance.",
"Uses hashing.",
"Not synchronized.",
"Backed by HashMap."
],
tanglish:"Order mukkiyam illa."
},
{
id:47,cat:"Collections",q:"Map Interface",
points:[
"Key-value pairs.",
"No duplicate keys.",
"Allows null key.",
"Values can duplicate.",
"Fast lookup.",
"Not part of Collection.",
"Used in caching."
],
tanglish:"Key-value store."
},
{
id:48,cat:"Collections",q:"HashMap",
points:[
"Unordered.",
"One null key.",
"Multiple null values.",
"Not synchronized.",
"Fast.",
"Uses hashing.",
"Most used map."
],
tanglish:"General purpose map."
},
{
id:49,cat:"Collections",q:"Hashtable",
points:[
"Synchronized.",
"No null key.",
"No null value.",
"Thread-safe.",
"Slower than HashMap.",
"Legacy class.",
"Used in multithreading."
],
tanglish:"Thread safe."
},
{
id:50,cat:"Collections",q:"Comparable vs Comparator",
points:[
"Comparable natural order.",
"Comparator custom order.",
"Comparable inside class.",
"Comparator external.",
"compareTo method.",
"compare method.",
"Sorting control."
],
tanglish:"Custom sort na Comparator."
},

/* ================= MULTITHREADING (61–70) ================= */
{
id:61,cat:"Multithreading",q:"Thread",
points:[
"Lightweight process.",
"Concurrent execution.",
"Shares memory.",
"Improves CPU usage.",
"Faster execution.",
"Java supports threads.",
"Inside process."
],
tanglish:"Parallel execution."
},
{
id:62,cat:"Multithreading",q:"Runnable",
points:[
"Functional interface.",
"run() method.",
"Supports multiple inheritance.",
"Better design.",
"Memory efficient.",
"Preferred approach.",
"Decouples logic."
],
tanglish:"Best practice."
},
{
id:63,cat:"Multithreading",q:"Synchronization",
points:[
"Ensures thread safety.",
"Prevents race condition.",
"Locks shared resource.",
"Uses synchronized keyword.",
"Ensures consistency.",
"Reduces concurrency.",
"Performance cost."
],
tanglish:"Shared data safe."
},
{
id:64,cat:"Multithreading",q:"Deadlock",
points:[
"Threads wait forever.",
"Circular dependency.",
"Resource locking issue.",
"Application freeze.",
"Hard to debug.",
"Occurs in sync.",
"Avoid by ordering."
],
tanglish:"Thread stuck."
},
{
id:65,cat:"Multithreading",q:"volatile keyword",
points:[
"Ensures visibility.",
"Used in multithreading.",
"Prevents caching.",
"Reads from main memory.",
"No atomicity guarantee.",
"Used for flags.",
"Lightweight."
],
tanglish:"Update ellam visible."
},

/* ================= FILE IO & JDBC (71–100) ================= */
{
id:71,cat:"IO",q:"File Handling",
points:[
"Reads and writes files.",
"Uses java.io.",
"Supports text and binary.",
"Streams based.",
"Needs closing.",
"Handles external data.",
"Persistent storage."
],
tanglish:"File work panna."
},
{
id:72,cat:"IO",q:"Serialization",
points:[
"Object to byte stream.",
"Uses Serializable.",
"Saves object state.",
"Used in file/network.",
"JVM controlled.",
"transient ignored.",
"Persistent."
],
tanglish:"Object save."
},
{
id:73,cat:"IO",q:"Deserialization",
points:[
"Byte stream to object.",
"Restores object.",
"Reverse of serialization.",
"Uses ObjectInputStream.",
"Runtime process.",
"Maintains state.",
"JVM controlled."
],
tanglish:"Object thirumba."
},
{
id:74,cat:"JDBC",q:"What is JDBC?",
points:[
"Java Database Connectivity.",
"Connects Java and DB.",
"Executes SQL.",
"Platform independent.",
"Uses drivers.",
"Supports CRUD.",
"java.sql package."
],
tanglish:"Java-DB bridge."
},
{
id:75,cat:"JDBC",q:"JDBC Architecture",
points:[
"Java application.",
"JDBC API.",
"JDBC Driver.",
"DriverManager.",
"Database.",
"Layered structure.",
"DB independent."
],
tanglish:"JDBC layers."
},
{
id:76,cat:"JDBC",q:"JDBC Drivers",
points:[
"Type 1 ODBC.",
"Type 2 Native.",
"Type 3 Network.",
"Type 4 Thin.",
"Type 4 preferred.",
"Platform independent.",
"Better performance."
],
tanglish:"Thin driver best."
},
{
id:77,cat:"JDBC",q:"Connection",
points:[
"Establishes DB connection.",
"Provided by DriverManager.",
"Session with DB.",
"Resource heavy.",
"Must be closed.",
"Thread unsafe.",
"Used to execute SQL."
],
tanglish:"DB connect."
},
{
id:78,cat:"JDBC",q:"Statement",
points:[
"Executes SQL queries.",
"Used for static queries.",
"Simple implementation.",
"SQL injection risk.",
"Less efficient.",
"Not reusable.",
"java.sql."
],
tanglish:"Simple query."
},
{
id:79,cat:"JDBC",q:"PreparedStatement",
points:[
"Precompiled SQL.",
"Faster execution.",
"Prevents SQL injection.",
"Reusable.",
"Supports parameters.",
"Better performance.",
"Preferred choice."
],
tanglish:"Secure and fast."
},
{
id:80,cat:"JDBC",q:"ResultSet",
points:[
"Holds query result.",
"Cursor based.",
"Row by row access.",
"Read-only default.",
"Connected to statement.",
"Used for data read.",
"java.sql."
],
tanglish:"Result store."
},
{
id:81,cat:"JDBC",q:"executeQuery vs executeUpdate",
points:[
"executeQuery returns ResultSet.",
"Used for SELECT.",
"executeUpdate returns int.",
"Used for INSERT/UPDATE.",
"Different purposes.",
"Affects rows.",
"JDBC methods."
],
tanglish:"Select vs update."
},
{
id:82,cat:"JDBC",q:"Transaction",
points:[
"Group of operations.",
"Atomic execution.",
"Commit or rollback.",
"Ensures consistency.",
"Important in banking.",
"JDBC supported.",
"ACID based."
],
tanglish:"All or nothing."
},
{
id:83,cat:"JDBC",q:"commit()",
points:[
"Saves changes.",
"Ends transaction.",
"Makes data permanent.",
"Used after success.",
"Manual control.",
"JDBC method.",
"Critical operation."
],
tanglish:"Data fix."
},
{
id:84,cat:"JDBC",q:"rollback()",
points:[
"Undo changes.",
"Used on failure.",
"Restores previous state.",
"Prevents corruption.",
"Transaction control.",
"JDBC method.",
"Safety mechanism."
],
tanglish:"Fail aana thirumba."
},
{
id:85,cat:"JDBC",q:"ACID Properties",
points:[
"Atomicity.",
"Consistency.",
"Isolation.",
"Durability.",
"Transaction safety.",
"Prevents data loss.",
"DB reliability."
],
tanglish:"Transaction rules."
},
{
id:86,cat:"JDBC",q:"Batch Processing",
points:[
"Multiple queries together.",
"Improves performance.",
"Reduces DB calls.",
"Used in bulk insert.",
"JDBC supported.",
"Efficient.",
"Faster execution."
],
tanglish:"Bulk work fast."
},
{
id:87,cat:"JDBC",q:"Connection Pooling",
points:[
"Reuses connections.",
"Improves performance.",
"Reduces overhead.",
"Used in enterprise apps.",
"Faster response.",
"Resource efficient.",
"Scalable."
],
tanglish:"Connection reuse."
},
{
id:88,cat:"JDBC",q:"SQL Injection",
points:[
"Malicious SQL attack.",
"Occurs via input.",
"Security threat.",
"Data theft risk.",
"Avoid using Statement.",
"Use PreparedStatement.",
"Validate inputs."
],
tanglish:"SQL hack."
},
{
id:89,cat:"JDBC",q:"try-with-resources",
points:[
"Auto closes resources.",
"Java 7 feature.",
"Cleaner code.",
"Prevents leaks.",
"Implements AutoCloseable.",
"Safer I/O.",
"Recommended."
],
tanglish:"Auto close."
},
{
id:90,cat:"JDBC",q:"AutoCloseable",
points:[
"Interface.",
"close() method.",
"Used in try-with-resources.",
"Ensures cleanup.",
"JDBC supported.",
"java.lang.",
"Resource safety."
],
tanglish:"Auto close support."
},
{
id:100,cat:"JDBC",q:"Real-time JDBC Usage",
points:[
"Login systems.",
"Banking transactions.",
"Inventory management.",
"CRUD operations.",
"Enterprise backend.",
"Secure data handling.",
"Database-driven apps."
],
tanglish:"Real project DB work."
},
{
  id: 101,
  cat: "Java Basics",
  q: "What are Primitive Data Types?",
  points: [
    "Primitive data types store simple, single values.",
    "They are predefined in Java and not objects.",
    "They store actual values, not references.",
    "They are faster and use less memory.",
    "They cannot call methods or have properties.",
    "There are 8 primitive data types in Java.",
    "Used for basic data handling and performance-critical code."
  ],
  tanglish: "Simple value store pannura basic datatype; object illa."
},
{
  id: 102,
  cat: "Java Basics",
  q: "What are Non-Primitive Data Types?",
  points: [
    "Non-primitive data types store complex data.",
    "They are created by programmers or provided by Java.",
    "They store references to memory locations.",
    "They can store multiple values and structures.",
    "They have methods and properties.",
    "They are stored in heap memory.",
    "Examples include String, Array, Class, and Interface."
  ],
  tanglish: "Reference store pannura complex datatype; methods irukkum."
},
{
  id: 103,
  cat: "Java Basics",
  q: "What are Access Modifiers in Java?",
  points: [
    "Access modifiers control the visibility of classes, methods, and variables.",
    "They define where a member can be accessed from.",
    "They help achieve encapsulation and security.",
    "Java has four types of access modifiers.",
    "They prevent unauthorized access to data.",
    "They are decided at compile time.",
    "Commonly used in enterprise and layered applications."
  ],
  tanglish: "Access modifiers na yaaru enga access panna mudiyum nu control pannrathu."
},

{
  id: 104,
  cat: "Java Basics",
  q: "public Access Modifier",
  points: [
    "public members are accessible from anywhere.",
    "They can be accessed inside and outside the package.",
    "There are no access restrictions.",
    "Mostly used for APIs and service methods.",
    "Classes declared as public can be reused across projects.",
    "Overuse can reduce security.",
    "Common in controllers and utility classes."
  ],
  tanglish: "Enga irundhaalum access panna mudiyum."
},
{
  id: 105,
  cat: "Java Basics",
  q: "private Access Modifier",
  points: [
    "private members are accessible only within the same class.",
    "They cannot be accessed from outside the class.",
    "Used to hide internal implementation details.",
    "Helps achieve strong encapsulation.",
    "Mostly used for variables.",
    "Access is usually provided via getters and setters.",
    "Improves security and control over data."
  ],
  tanglish: "Same class kulla mattum thaan access."
},
{
  id: 106,
  cat: "Java Basics",
  q: "protected Access Modifier",
  points: [
    "protected members are accessible within the same package.",
    "They can also be accessed by subclasses outside the package.",
    "Used mainly in inheritance scenarios.",
    "Offers more access than private but less than public.",
    "Helps in controlled extension of classes.",
    "Not accessible without inheritance from outside package.",
    "Common in framework-level classes."
  ],
  tanglish: "Same package illa subclass irundhaa access pannalaam."
},
{
  id: 107,
  cat: "Java Basics",
  q: "default Access Modifier",
  points: [
    "Default access is applied when no modifier is specified.",
    "Members are accessible only within the same package.",
    "Not accessible outside the package.",
    "Also called package-private access.",
    "Used for internal package-level logic.",
    "Helps limit exposure without using private.",
    "Common in utility and helper classes."
  ],
  tanglish: "Same package kulla mattum access."
},

{
  id: 108,
  cat: "Java Basics",
  q: "Difference Between break, continue, and exit",
  points: [
    "break terminates the current loop or switch statement.",
    "continue skips the current iteration and moves to the next iteration of the loop.",
    "exit stops the entire program execution immediately.",
    "break is commonly used in loops and switch cases.",
    "continue is used only inside loops.",
    "exit is used when the program must end completely.",
    "break and continue affect loops; exit affects the JVM process."
  ],
  tanglish: "break loop-ah niruthum, continue oru round skip pannum, exit full program-a close pannum."
},
{
  id: 109,
  cat: "Java Basics",
  q: "Static Method vs Non-Static Method",
  points: [
    "Static methods belong to the class, not to objects.",
    "Non-static methods belong to an instance of the class.",
    "Static methods can be called without creating an object.",
    "Non-static methods require object creation.",
    "Static methods cannot access non-static members directly.",
    "Non-static methods can access both static and non-static members.",
    "Static methods are used for common or utility logic."
  ],
  tanglish: "Static method object venam; non-static method-ku object thevai."
},
{
  id: 110,
  cat: "Java Basics",
  q: "What is a Method in Java?",
  points: [
    "A method is a block of code that performs a specific task.",
    "It is used to reuse code and reduce duplication.",
    "Methods can take input parameters.",
    "Methods can return a value or be void.",
    "They improve readability and maintainability of code.",
    "Methods are defined inside a class.",
    "They are executed when they are called."
  ],
  tanglish: "Oru specific work panna use aagura code block thaan method."
},
{
  id: 111,
  cat: "Java Basics",
  q: "What are Variables in Java?",
  points: [
    "Variables are used to store data values.",
    "They act as containers for information in a program.",
    "Each variable has a data type.",
    "Variables must be declared before use.",
    "They help manipulate and reuse data.",
    "Values of variables can change during execution.",
    "They improve flexibility and readability of code."
  ],
  tanglish: "Value store panna use aagura container thaan variable."
},
{
  id: 112,
  cat: "Java Basics",
  q: "What is SCP (String Constant Pool)?",
  points: [
    "String Constant Pool is a special memory area in heap.",
    "It stores String literals to optimize memory usage.",
    "Same string literal is not created multiple times.",
    "If a string already exists in SCP, reference is reused.",
    "It improves performance and reduces memory overhead.",
    "Strings created using literals go to SCP.",
    "Strings created using new keyword go to heap, not SCP."
  ],
  tanglish: "Same string repeated-aa use panna memory save panna irukkura special area thaan SCP."
},
{
  id: 113,
  cat: "Java Basics",
  q: "Types of Variables in Java",
  points: [
    "Java has three main types of variables.",
    "Local variables are declared inside methods or blocks.",
    "Instance variables are declared inside a class but outside methods.",
    "Static variables are declared using the static keyword.",
    "Local variables must be initialized before use.",
    "Instance and static variables get default values.",
    "Variable type decides scope, lifetime, and memory location."
  ],
  tanglish: "Local, Instance, Static nu moonu type variables irukku."
},

{
  id: 114,
  cat: "Java Basics",
  q: "What is Type Casting?",
  points: [
    "Type casting is converting one data type into another.",
    "It is mainly used with primitive data types.",
    "There are two types of type casting in Java.",
    "Widening casting is automatic and safe.",
    "Narrowing casting is manual and may cause data loss.",
    "Type casting helps in data compatibility.",
    "Used in arithmetic operations and assignments."
  ],
  tanglish: "Oru datatype value-a vera datatype-ku change pannrathu thaan type casting."
},
{
  id: 115,
  cat: "Java Basics",
  q: "What are Literals in Java?",
  points: [
    "Literals are fixed values assigned to variables.",
    "They represent constant values in source code.",
    "Literals directly appear in the program.",
    "They do not change during execution.",
    "Java supports different types of literals.",
    "Examples include integer, floating, character, and string literals.",
    "Used to initialize variables easily."
  ],
  tanglish: "Direct-aa code-la value kudukkarathu thaan literal."
},

{
  id: 116,
  cat: "OOP Concepts",
  q: "Types of Polymorphism in Java",
  points: [
    "Polymorphism means one method with many forms.",
    "Java supports two main types of polymorphism.",
    "Compile-time polymorphism is achieved using method overloading.",
    "Method overloading happens within the same class.",
    "Runtime polymorphism is achieved using method overriding.",
    "Method overriding depends on inheritance.",
    "Runtime polymorphism is resolved at runtime using dynamic binding."
  ],
  tanglish: "Compile-time (overloading) & Runtime (overriding) thaan polymorphism types."
},
{
  id: 117,
  cat: "OOP Concepts",
  q: "Types of Inheritance in Java",
  points: [
    "Inheritance allows one class to acquire properties of another class.",
    "Java supports Single inheritance.",
    "Java supports Multilevel inheritance.",
    "Java supports Hierarchical inheritance.",
    "Multiple inheritance is not supported using classes in Java.",
    "Hybrid inheritance is not directly supported using classes.",
    "Multiple and hybrid inheritance can be achieved using interfaces."
  ],
  tanglish: "Java-la single, multilevel, hierarchical irukku; multiple interface use pannalaam."
},



];

   

export default function InterviewFAQ() {
  const [search, setSearch] = useState("");
  const [openId, setOpenId] = useState(null);

  const filtered = useMemo(() => {
    return FAQ_DATA.filter(item => 
      item.q.toLowerCase().includes(search.toLowerCase()) ||
      item.cat.toLowerCase().includes(search.toLowerCase())
    );
  }, [search]);

 return (
    /* Responsive Container: px-4 ensures padding on small mobile screens */
    <div className="max-w-7xl mx-auto space-y-8 md:space-y-12 pb-20 md:pb-32 pt-6 md:pt-10 px-4 md:px-6 font-sans bg-white">
      
      {/* 1. HEADER SECTION - Responsive text sizes */}
      <section className="text-center space-y-4">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-slate-900 text-white text-[10px] font-black uppercase tracking-[0.2em]">
           <ShieldCheck className="w-4 h-4 text-orange-400" /> Professional Java Guide
        </div>
        <h1 className="text-4xl md:text-7xl font-black text-slate-900 tracking-tighter leading-tight">
          Interview <span className="text-orange-600 italic text-shadow-orange">Bible</span>
        </h1>
        <p className="text-slate-500 text-sm md:text-lg font-medium max-w-2xl mx-auto">
          Master 100+ concepts with <strong>Simple Summaries</strong> and technical depth for your next career move.
        </p>
      </section>

      {/* 2. STICKY SEARCH BAR - Responsive width */}
      {/* <div className="sticky top-4 md:top-[75px] z-30 max-w-2xl mx-auto transition-all">
        <div className="relative bg-white/80 backdrop-blur-md border-2 border-slate-100 rounded-[1.5rem] md:rounded-[2rem] shadow-2xl p-1 md:p-2 flex items-center">
           <Search className="ml-4 text-slate-400 w-5 h-5" />
           <input 
              type="text"
              placeholder="Search by topic..."
              className="w-full px-4 py-3 border-none focus:ring-0 font-bold text-slate-700 text-sm md:text-base bg-transparent"
              onChange={(e) => setSearch(e.target.value)}
           />
        </div>
      </div> */}

      {/* 3. FAQ LISTING - Optimized for Mobile Taps */}
      <div className="grid grid-cols-1 gap-4 md:gap-6">
        {filtered.map((item) => (
          <div 
            key={item.id}
            className={`border-2 transition-all duration-500 rounded-[1.5rem] md:rounded-[3rem] overflow-hidden ${
              openId === item.id ? "border-orange-500 bg-white shadow-xl" : "border-slate-50 bg-slate-50/50 hover:border-slate-200"
            }`}
          >
            <button 
              onClick={() => setOpenId(openId === item.id ? null : item.id)}
              className="w-full text-left px-6 md:px-10 py-6 md:py-8 flex items-center justify-between gap-4"
            >
              <div className="flex items-center gap-4 md:gap-6">
                <span className="text-2xl md:text-4xl font-black text-slate-200 shrink-0">
                  {String(item.id).padStart(2, '0')}
                </span>
                <div>
                  <span className="text-[9px] md:text-[10px] font-black uppercase tracking-widest text-orange-600 mb-1 block">{item.cat}</span>
                  <h3 className="text-lg md:text-2xl font-black text-slate-900 tracking-tight leading-tight">{item.q}</h3>
                </div>
              </div>
              <div className={`p-2 rounded-full shrink-0 ${openId === item.id ? "bg-orange-600 text-white" : "bg-white text-slate-400 shadow-sm"}`}>
                <ChevronDown className={`w-5 h-5 md:w-6 md:h-6 transition-transform duration-500 ${openId === item.id ? "rotate-180" : ""}`} />
              </div>
            </button>

            {openId === item.id && (
              <div className="px-6 md:px-10 pb-8 md:pb-12 space-y-8 animate-in fade-in slide-in-from-top-4 duration-500">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 md:gap-10">
                  
                  {/* TECHNICAL POINTS */}
                  <div className="space-y-4">
                    <h5 className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center gap-2">
                      <Terminal className="w-4 h-4 text-orange-500" /> Technical Breakdown
                    </h5>
                    <ul className="space-y-3">
                      {item.points.map((p, i) => (
                        <li key={i} className="flex items-start gap-3">
                          <CheckCircle2 className="mt-1 w-4 h-4 text-orange-500 shrink-0" />
                          <p className="text-slate-600 text-sm md:text-base font-medium leading-relaxed">{p}</p>
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* SUMMARY BOX - Stacks below on mobile */}
                  <div className="relative group">
                    <div className="absolute inset-0 bg-slate-900 rounded-[2rem] md:rounded-[2.5rem] transform md:rotate-1 group-hover:rotate-0 transition-transform" />
                    <div className="relative bg-slate-800 p-6 md:p-8 rounded-[2rem] md:rounded-[2.5rem] h-full flex flex-col justify-center border border-slate-700 shadow-2xl">
                      <div className="flex items-center gap-2 text-orange-400 font-black text-[10px] uppercase tracking-widest mb-4">
                         <Star className="w-4 h-4 fill-current" /> Instant Recall
                      </div>
                      <p className="text-xl md:text-2xl font-bold text-white leading-snug italic">
                        "{item.tanglish}"
                      </p>
                      <div className="mt-6 flex gap-2">
                        <div className="w-8 h-1 bg-orange-500 rounded-full" />
                        <div className="w-4 h-1 bg-slate-600 rounded-full" />
                        <div className="w-4 h-1 bg-slate-600 rounded-full" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* 4. MASTER FOOTER - Full width on all devices */}
      <footer className="p-8 md:p-16 bg-slate-900 rounded-[2.5rem] md:rounded-[4rem] text-center space-y-6 shadow-2xl border-b-8 border-orange-500">
          <Database className="w-10 h-10 md:w-12 md:h-12 text-orange-500 mx-auto" />
          <h2 className="text-2xl md:text-4xl font-black text-white tracking-tighter">Your Journey Continues</h2>
          <p className="text-slate-400 text-sm md:text-base max-w-xl mx-auto leading-relaxed">
            Memorizing is just the first step. Practice coding these concepts every day to build the muscle memory needed for <strong>Senior Level Interviews</strong>.
          </p>
          <div className="flex justify-center gap-4">
            <div className="px-4 py-2 bg-white/5 rounded-full border border-white/10 text-[10px] text-orange-400 font-black uppercase tracking-widest">
              12 Modules
            </div>
            <div className="px-4 py-2 bg-white/5 rounded-full border border-white/10 text-[10px] text-orange-400 font-black uppercase tracking-widest">
              100+ Topics
            </div>
          </div>
      </footer>

    </div>
  );
}
